# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pre-Release
on:
  release:
    types:
      - prereleased
  workflow_dispatch:

env:
  #ARTIFACTS_API_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  #ARTIFACTS_FEED_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  #VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'
  MANIFEST_FILE: "_manifest/spdx_2.2/manifest.spdx.json"
  PACKAGE_NAME: "ed-fi-kafka-connect-transforms"
  #IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  #DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  #DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  REF: ${{ github.ref_name }}

permissions: read-all

jobs:
  pack:
    name: Build and Pack
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    outputs:
      hash-code: ${{ steps.hash-code.outputs.hash-code }}
      dms-version: ${{ steps.versions.outputs.dms-v }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set Version Numbers
        id: versions
        run: |
          Import-Module ./package-helpers.psm1
          Get-VersionNumber

      - name: Publish Jar Package
        run: |
          $packageVersion = "${{ steps.versions.outputs.dms-semver }}"
          pwd
          ls  
        #gradle init
        #gradle installDist --no-daemon

      #./build.ps1 -Command BuildAndPublish `
      #        -Configuration Release `
      #        -DMSVersion $packageVersion

      #NOT Need it, review if war is required
      #- name: Create NuGet Package
      #  run: |
      #    $packageVersion = "${{ steps.versions.outputs.dms-semver }}"

          #./build.ps1 -Command Package `
           #   -DMSVersion $packageVersion `
            #  -Configuration Release

      #- name: Generate hash for NuGet package
      #  id: hash-code
      #  run: |
      #    "hash-code=$(sha256sum *.nupkg | base64 -w0)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload Packages as Artifacts
        if: success()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          #name: "${{ env.PACKAGE_NAME }}"
          name: "ed-fi-kafka-connect-transforms-"
          path: ${{ github.workspace }}/*.jar
          if-no-files-found: error
          retention-days: 30
